name: build-push-action
on:
  push:

jobs:
  build-push-action:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
      -
        name: Build container-1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./container-1/Dockerfile
          push: false
          load: true
          tags: antmerl/container-1:latest
      - 
        name: Docker Inspect
        run: |
          docker image ls
          docker image inspect antmerl/container-1
      -
        name: Build container-2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./container-2/Dockerfile
          push: false
          load: true
          tags: antmerl/container-2:latest
